AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Parameters:
    env:
        Type: String
        Default: dev
        AllowedValues:
            - dev
            - prod
    Lambda1Arn:
        Type: String
    Lambda2Arn:
        Type: String
    ErrorHandlerArn:
        Type: String

Resources:
    #######################################################################################
    # Step function
    #######################################################################################
    StepFunction:
        Type: AWS::Serverless::StateMachine
        Properties:
            Name: demo-step-function
            Definition:
                Comment: domo step function
                StartAt: Lambda1
                States:
                    Lambda1:
                        Type: Task
                        Resource: arn:aws:states:::lambda:invoke
                        OutputPath: $.Payload
                        Parameters:
                            Payload.$: $
                            FunctionName: !Ref Lambda1Arn
                        Catch:
                            - ErrorEquals:
                                  - States.ALL
                              Comment: Report Input ERROR
                              Next: ErrorHandler
                              ResultPath: $
                        Next: Lambda2

                    Lambda2:
                        Type: Task
                        Resource: arn:aws:states:::lambda:invoke
                        OutputPath: $.Payload
                        Parameters:
                            Payload.$: $
                            FunctionName: !Ref Lambda2Arn
                        Catch:
                            - ErrorEquals:
                                  - States.ALL
                              Comment: Report Input ERROR
                              Next: ErrorHandler
                              ResultPath: $
                        End: true

                    ErrorHandler:
                        Type: Task
                        Resource: arn:aws:states:::lambda:invoke
                        OutputPath: $.Payload
                        Parameters:
                            Payload.$: $
                            FunctionName: !Ref ErrorHandlerArn
                        End: true
            Tracing:
                Enabled: true
            Policies:
                - Statement:
                      - Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource:
                            - !Ref Lambda1Arn
                            - !Ref Lambda2Arn
                            - !Ref ErrorHandlerArn
            Events:
                ScheduledEvent:
                    Type: ScheduleV2
                    Properties:
                        ScheduleExpression: cron(0 6 ? * MON-FRI *)
                        ScheduleExpressionTimezone: America/Los_Angeles
                        State: ENABLED
                        Description: "Daily trigger for Demo Report at 6 AM PST"
                        Input: '{"reportType":"yesterday","fromDate":"","toDate":"","offsetHour":"-7","request":{"fileType":"txt","fileName":"Demo_File_Name","includeDateTimeInFileName":true,"isEncrypted":false,"isCompressed":true,"delimiter":"|","createFileControl":false},"uploadFileToS3Bucket":"internal-for-test","encryptedKeyFromS3":"{{s3Bucket}}/{{s3Key}}","sendFileTo":[{"sendFileType":"email","sendFiles":["txt.gz"],"sendFileConfig":[{"fromEmail":"pindihoc@gmail.com","toEmail":"pindihoc@gmail.com","subject":"Demo step function - Success","html":"Success"}]}],"dbConfig":{"name":"db_name","sqlConfig":{"user":"{{user}}","password":"{{password}}","server":"{{server_url}}","database":"{{db_name}}","port":1433,"dialect":"mssql","options":{"trustServerCertificate":true}},"queryParams":["@fromDate","@toDate","@offsetHour"],"queryString":"EXEC [dbo].[SP_demo] fromDate toDate offsetHour"}}'

Outputs:
    StepFunctionArn:
        Description: Step Function ARN
        Value: !Ref StepFunction